# Generated by Django 2.1.5 on 2019-02-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_shared_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_photos',
            name='others',
            field=models.BooleanField(default=True),
        ),
    ]
