# Generated by Django 2.1.5 on 2019-02-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_shared_photos_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_photos',
            name='session_key',
            field=models.TextField(default='1'),
        ),
    ]
