# Generated by Django 2.1.5 on 2019-02-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_photo_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='share',
        ),
    ]
