# Generated by Django 2.1.5 on 2019-02-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_shared_photos_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
